# -*- coding: utf-8 -*-
"""projeto-algoritomo-de-altoria-de-dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqkqwRfme7FsfupUo4rO38W5ZkO3ythr
"""

#configuracção global

LIMITE_SEGURANCA = 1000.0

# Entrada de dados e Casting

venda1 = float(input("Digite o Valor da 1ª venda: "))
venda2 = float(input("Digite o Valor da 2ª venda: "))
venda3 = float(input("Digite o Valor da 3ª venda: "))

# Processamento interno (Escopo)

def analisar_vendas(v1, v2, v3):
    global LIMITE_SEGURANCA
# Calculo da média simples

    media = (v1 + v2 + v3) / 3
    print(f"\nmedia das vendas: RS {media:.2f}")

# Lógica de Investigação

    if media > LIMITE_SEGURANCA:
      print ("SISTEMA EM QUARENTENA")

# Verificar discrepância (5x maior que a média)

    if v1 > 5 * media or v2 > 5 * media or v3 > 5 * media:
      print("REVISÃO MANUAL NECESSÁRIA")

# Permitir ajuste do limite caso necessário

    if v1 > LIMITE_SEGURANCA or v2 > LIMITE_SEGURANCA or v3 > LIMITE_SEGURANCA:
      resposta = input("Venda acima do limite detectada. Deseja ajustar o LIMITE_SEGURANCA? (s/n): ")
    if resposta.lower() == 's':
      novo_limite = float(input("Digite o novo limite: "))
      LIMITE_SEGURANCA = novo_limite
      print(f"Novo LIMITE_SEGURANCA definido: RS {LIMITE_SEGURANCA:.2f}")

# Apresentação dos tipos de dados

    print("\n--- Tipos de Dados ---")
    print(f"venda1: {v1} -> {type(v1)}")
    print(f"venda2: {v2} -> {type(v2)}")
    print(f"venda3: {v3} -> {type(v3)}")
    print(f"media: {media} -> {type(media)}")
    print(f"LIMITE_SEGURANCA: {LIMITE_SEGURANCA} -> {type(LIMITE_SEGURANCA)}")
# Execução
analisar_vendas(venda1, venda2, venda3)