# -*- coding: utf-8 -*-
"""projeto-analisador-de-clima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQR92VZN1bqq_dPT7wIVyZLcKhDXPVcQ
"""

def analisar_clima():

  soma_temperaturas: float = 0.0

  dias_quentes: int = 0

  alerta_extremo: bool = False



  for dia in range(1, 8):

    temp: float = float(input(f"Digite a temperatura do dia {dia}: "))

    soma_temperaturas += temp



    if temp > 35.0:

      dias_quentes += 1



    if temp > 45.0 or temp < -5.0:

      alerta_extremo = True



  media: float = soma_temperaturas / 7

  print(f"Média semanal: {media:.1f}°C")

  print(f"Dias acima de 35°C: {dias_quentes}")



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")





if __name__ == "__main__":

  analisar_clima()