# -*- coding: utf-8 -*-
"""projeto_logica_para_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vtr6Pcx7wGzbQsV5PZJBW4incdttezd
"""

def processar_vendas():

  total_compra: float = 0.0

  itens_comprados: int = 0



  quantidade_tipos: int = int(input("Quantos produtos diferentes foram comprados? "))



  for i in range(1, quantidade_tipos + 1):

    nome: str = input("Nome do produto: ")

    preco: float = float(input("Preço unitário: "))

    qtd: int = int(input("Quantidade deste produto: "))



    if preco <= 0 or qtd <= 0:

      print(f"Erro: Valores inválidos para {nome}")

    else:

      subtotal: float = preco * qtd

      total_compra += subtotal

      itens_comprados += qtd



  if total_compra > 500.00:

    total_final: float = total_compra * 0.90

    print("Desconto de 10% aplicado!")

  elif total_compra > 200.00:

    total_final = total_compra * 0.95

    print("Desconto de 5% aplicado!")

  else:

    total_final = total_compra



  print(f"Resumo: {itens_comprados} itens. Total a pagar: R$ {total_final:.2f}")





if __name__ == "__main__":

  processar_vendas()

def analisar_clima():

  soma_temperaturas: float = 0.0

  dias_quentes: int = 0

  alerta_extremo: bool = False



  for dia in range(1, 8):

    temp: float = float(input(f"Digite a temperatura do dia {dia}: "))

    soma_temperaturas += temp



    if temp > 35.0:

      dias_quentes += 1



    if temp > 45.0 or temp < -5.0:

      alerta_extremo = True



  media: float = soma_temperaturas / 7

  print(f"Média semanal: {media:.1f}°C")

  print(f"Dias acima de 35°C: {dias_quentes}")



  if alerta_extremo:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")





if __name__ == "__main__":

  analisar_clima()

def sistema_notas_turma():

  total_alunos: int = int(input("Quantos alunos existem na turma? "))



  for j in range(1, total_alunos + 1):

    aluno_nome: str = input("Nome do aluno: ")

    n1: float = float(input("Nota 1: "))

    n2: float = float(input("Nota 2: "))



    media_aluno: float = (n1 + n2) / 2



    if media_aluno >= 7.0:

      print(f"{aluno_nome}: Aprovado com média {media_aluno:.1f}")

    elif media_aluno >= 5.0:

      print(f"{aluno_nome}: Recuperação (Média: {media_aluno:.1f})")

    else:

      print(f"{aluno_nome}: Reprovado (Média: {media_aluno:.1f})")





if __name__ == "__main__":

  sistema_notas_turma()

def simulador_poupanca():

  saldo: float = float(input("Valor inicial do investimento: R$ "))

  taxa: float = float(input("Taxa de juros mensal (em %): "))

  meses: int = int(input("Número de meses da simulação: "))



  meta_atingida: bool = False



  for m in range(1, meses + 1):

    aporte: float = float(input(f"Quanto deseja depositar no mês {m}? (0 para nenhum): R$ "))



    saldo += aporte

    juros: float = saldo * (taxa / 100)

    saldo += juros



    print(f"Mês {m:>3}: Saldo atualizado = R$ {saldo:>12,.2f} | Juros do mês: R$ {juros:.2f}")



    if saldo > 10_000.0 and not meta_atingida:

      print(f" Parabéns! Você atingiu a meta de R$ 10.000 no mês {m}!")

      meta_atingida = True



  print("-" * 50)

  print(f"Resultado final após {meses} meses: R$ {saldo:,.2f}")





if __name__ == "__main__":

  simulador_poupanca()