# -*- coding: utf-8 -*-
"""projeto_criador_de_emojis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bh5tI1LoLsgd5wbwOgaYGaX_5vHxV0D0
"""

import matplotlib.pyplot as plt

emoji_data = {
    "grade": [
        [(255, 255, 0), (255, 255, 0), (0, 0, 0)],
        [(255, 255, 0), (0, 0, 0), (255, 255, 0)],
        [(255, 255, 0), (255, 255, 0), (255, 255, 0)]
    ]
}

nova_grade = []

for chave, valor in emoji_data.items():

    if chave == "grade":

        for linha in valor:

            nova_linha = []

            for pixel in linha:

                if pixel == (255, 255, 0):

                    novo_pixel = (
                        pixel[0] // 2,
                        pixel[1] // 2,
                        pixel[2] // 2
                    )

                else:
                    novo_pixel = pixel

                nova_linha.append(novo_pixel)

            nova_grade.append(nova_linha)

emoji_data["grade"] = nova_grade

for linha in emoji_data["grade"]:
    print(linha)

plt.imshow(emoji_data["grade"])
plt.axis("off")
plt.show()