# -*- coding: utf-8 -*-
"""projeto_sistema_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8PowAgdSzWA74t_SC9gdpZqDjFEFZIj
"""

import time

def auditor(funcao):
    def wrapper(*args, **kwargs):
        print("\n INICIANDO AUDITORIA FINANCEIRA")

        inicio = time.time()

        print("\n Argumentos recebidos:")
        print(f"- Args: {args}")
        print(f"- Kwargs: {kwargs}")

        resultado = funcao(*args, **kwargs)

        fim = time.time()
        tempo_total = fim - inicio

        print("\n Auditoria finalizada!")
        print(f" Tempo de execução: {tempo_total:.6f} segundos")


        return resultado

    return wrapper

empresa_data = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 50000,
                "Seguranca": 30000
            },
            "Desenvolvimento": {
                "Frontend": 20000,
                "Backend": 25000,
                "DevOps": 15000
            }
        },
        "RH": {
            "Recrutamento": 10000,
            "Treinamento": 12000,
            "Cultura": {
                "Eventos": 5000,
                "Brindes": 2000
            }
        },
        "Financeiro": {
            "Contabilidade": 90000,
            "Auditoria": 70000
        }
    }
}

@auditor

def calcular_orcamento(estrutura, *departamentos_ignorados, **conversao):
    total = 0

    for departamento, valor in estrutura.items():

        if departamento in departamentos_ignorados:
            print(f"\n Departamento ignorado: {departamento}")
            continue

        if isinstance(valor, dict):
            total += calcular_orcamento(
                valor,
                *departamentos_ignorados,
                **conversao
            )

        else:
            print(f" Somando orçamento de {departamento}: R${valor}")
            total += valor

    taxa = conversao.get("taxa_cambio", 1)
    moeda = conversao.get("moeda_destino", "BRL")

    return total * taxa


valor_total = calcular_orcamento(
    empresa_data,
    "RH",
    "Marketing",
    moeda_destino="BRL",
    taxa_cambio=1
)

print(f"\n Orçamento final convertido: R${valor_total:.2f}")