# -*- coding: utf-8 -*-
"""projeto-sistema-de-notas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRCjpqIMOFMXD-nKOpF8NV5q90x2y8py
"""

def sistema_notas_turma():

  total_alunos: int = int(input("Quantos alunos existem na turma? "))



  for j in range(1, total_alunos + 1):

    aluno_nome: str = input("Nome do aluno: ")

    n1: float = float(input("Nota 1: "))

    n2: float = float(input("Nota 2: "))



    media_aluno: float = (n1 + n2) / 2



    if media_aluno >= 7.0:

      print(f"{aluno_nome}: Aprovado com média {media_aluno:.1f}")

    elif media_aluno >= 5.0:

      print(f"{aluno_nome}: Recuperação (Média: {media_aluno:.1f})")

    else:

      print(f"{aluno_nome}: Reprovado (Média: {media_aluno:.1f})")





if __name__ == "__main__":

  sistema_notas_turma()