# -*- coding: utf-8 -*-
"""projeto-simulador-de-popanca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROy6hr98gYMyZBegZ89qlpSw42hD66nT
"""

def simulador_poupanca():

  saldo: float = float(input("Valor inicial do investimento: R$ "))

  taxa: float = float(input("Taxa de juros mensal (em %): "))

  meses: int = int(input("Número de meses da simulação: "))



  meta_atingida: bool = False



  for m in range(1, meses + 1):

    aporte: float = float(input(f"Quanto deseja depositar no mês {m}? (0 para nenhum): R$ "))



    saldo += aporte

    juros: float = saldo * (taxa / 100)

    saldo += juros



    print(f"Mês {m:>3}: Saldo atualizado = R$ {saldo:>12,.2f} | Juros do mês: R$ {juros:.2f}")



    if saldo > 10_000.0 and not meta_atingida:

      print(f" Parabéns! Você atingiu a meta de R$ 10.000 no mês {m}!")

      meta_atingida = True



  print("-" * 50)

  print(f"Resultado final após {meses} meses: R$ {saldo:,.2f}")





if __name__ == "__main__":

  simulador_poupanca()