# -*- coding: utf-8 -*-
"""projeto-algoritmo do-microclima-local.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvNJQqlC-Nf6zLPyEav0kcmaUd0DYIFi
"""

import math





def executar_analise():

  dados_locais = [

    ["Praça Brasil",  30, 57, 44],

    ["Metro Itaquera", 27, 73, 45],

    ["Terminal Carrao", 29, 50, 40],

  ]



  rotulos = ["Temperatura (C)", "IQA", "Umidade(%)"]

  resultados = []



  print("Analise de qualidade do ar e conforto urbano")



  for dados in dados_locais:

    local  = dados[0]

    metricas = dados[1:]



    print(f"\nLocal: {local}")



    for i, valor in enumerate(metricas):

      print(f" {rotulos[i]}: {valor}")



    temperatura, umidade, iqa = metricas



    # Classificacao do IQA (escala CETESB)

    match True:

      case _ if iqa <= 40:

        qualidade = "Boa"

      case _ if iqa <= 80:

        qualidade = "Moderada"

      case _ if iqa <= 120:

        qualidade = "Ruim"

      case _ if iqa <= 200:

        qualidade = "Muito Ruim"

      case _:

        qualidade = "Pessima"



    # Nota de Conforto Urbano (0 a 10)

    nota_temp = math.exp(-((temperatura - 22) ** 2) / 50)

    nota_umid = max(0.0, 1 - (umidade - 55) ** 2 / 1000)

    nota_iqa = max(0.0, 1 - (iqa / 200))

    nota   = round((0.40 * nota_temp + 0.30 * nota_umid + 0.30 * nota_iqa) * 10, 2)



    print(f" Qualidade do Ar (IQA {iqa}): {qualidade}")

    print(f" Nota de Conforto Urbano: {nota} / 10")



    if temperatura >= 30 or umidade < 40 or umidade > 80 or iqa > 80:

      print(" Recomendacao: evite exposicao prolongada neste local.")

    else:

      print(" Recomendacao: condicoes aceitaveis para atividades ao ar livre.")



    resultados.append((local, nota, qualidade))



executar_analise()