# -*- coding: utf-8 -*-
"""projeto_engenharia_de_contexto_e_logica_fisica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vtr6Pcx7wGzbQsV5PZJBW4incdttezd
"""

import math





def executar_analise():

  dados_locais = [

    ["Praça Brasil",  30, 57, 44],

    ["Metro Itaquera", 27, 73, 45],

    ["Terminal Carrao", 29, 50, 40],

  ]



  rotulos = ["Temperatura (C)", "IQA", "Umidade(%)"]

  resultados = []



  print("Analise de qualidade do ar e conforto urbano")



  for dados in dados_locais:

    local  = dados[0]

    metricas = dados[1:]



    print(f"\nLocal: {local}")



    for i, valor in enumerate(metricas):

      print(f" {rotulos[i]}: {valor}")



    temperatura, umidade, iqa = metricas



    # Classificacao do IQA (escala CETESB)

    match True:

      case _ if iqa <= 40:

        qualidade = "Boa"

      case _ if iqa <= 80:

        qualidade = "Moderada"

      case _ if iqa <= 120:

        qualidade = "Ruim"

      case _ if iqa <= 200:

        qualidade = "Muito Ruim"

      case _:

        qualidade = "Pessima"



    # Nota de Conforto Urbano (0 a 10)

    nota_temp = math.exp(-((temperatura - 22) ** 2) / 50)

    nota_umid = max(0.0, 1 - (umidade - 55) ** 2 / 1000)

    nota_iqa = max(0.0, 1 - (iqa / 200))

    nota   = round((0.40 * nota_temp + 0.30 * nota_umid + 0.30 * nota_iqa) * 10, 2)



    print(f" Qualidade do Ar (IQA {iqa}): {qualidade}")

    print(f" Nota de Conforto Urbano: {nota} / 10")



    if temperatura >= 30 or umidade < 40 or umidade > 80 or iqa > 80:

      print(" Recomendacao: evite exposicao prolongada neste local.")

    else:

      print(" Recomendacao: condicoes aceitaveis para atividades ao ar livre.")



    resultados.append((local, nota, qualidade))



executar_analise()

import time

import random





locais = [

  "Quarto dos fundos",

  "Porta do quarto",

  "Corredor da casa",

  "Porta da cozinha",

  "Cozinha",

  "Área externa",

  "Escada estreita",

  "Garagem",

  "Portão de saída",

  "RUA SAÍDA!",

]



estados = [

  "Caminho Livre",

  "porta aberta",

  "Caminho livre",

  "porta aberta",

  "virar à esquerda até a área externa",

  "virar à direita até o fim do corredor",

  "descer escada estreita até a garagem",

  "pegar a chave do portão na parede",

  "portão necessita de chave",

  "livre",

]



# ESTADO INICIAL DO AGENTE



posicao   = 0

inventario = []

energia   = 20

encontrou_saida = False



print("-" * 55)

print(" Simulador De Evacuação Agente Cego")

print("-" * 55)

print(f" Locais no mapa : {len(locais)}")

print(f" Energia inicial: {energia} ações")

print("-" * 55)

time.sleep(0.5)





while energia > 0 and not encontrou_saida:



  local_atual = locais[posicao]

  estado_atual = estados[posicao]



  print(f"\n[Energia: {energia:>2}] Local: {local_atual}")

  print(f"Estado : {estado_atual}")

  if inventario:

    print(f"Bolso: {', '.join(inventario)}")



  time.sleep(0.4)





  # NÓ FINAL

  if posicao == len(locais) - 1:

    print("\nAgente Chegou á Rua! Evacuação Bem Sucedida!")

    encontrou_saida = True

    break



  # NÓ: PORTÃO DE SAÍDA

  elif posicao == 8:

    if "chave do portão" in inventario:

      print("-> Agente usa a chave do portão. Portão aberto!")

      posicao += 1

    else:

      print(" ATENCAO: Portão TRANCADO! Agente não tem a chave.")

      print("-> Voltando para a garagem buscar a chave...")

      posicao -= 1



  # NÓ: GARAGEM

  elif posicao == 7:

    if "chave do portão" not in inventario:

      print("-> Agente encontra a chave do portão e a pega!")

      inventario.append("chave do portão")

    else:

      print("-> Chave já está na mochila. Seguindo em frente...")

    posicao += 1



  # NÓ: ESCADA ESTREITA

  elif posicao == 6:

    if random.random() < 0.20:

      print(" ATENCAO: Agente tropeça na escada! Perde 1 energia extra.")

      energia -= 1

    else:

      print("-> Agente desce a escada com cuidado.")

    posicao += 1



  # NÓ: PORTA ABERTA

  elif estado_atual == "porta aberta":

    print("-> Porta aberta! Agente passa sem obstáculo.")

    posicao += 1



  # NÓ: ANDAR / VIRAR

  else:

    print(f"-> Agente executa: {estado_atual}.")

    posicao += 1



  energia -= 1



# RESULTADO FINAL



print("\n" + "-" * 55)

if encontrou_saida:

  print("Simulação Concluida Agente Evacuado Com Sucesso")

  print(f"Energia restante : {energia} ações")



else:

  print("Simulação Encerrada Agente Ficou Sem Energia")

  print(f"Último local  : {locais[posicao]}")



print("-" * 55)