# -*- coding: utf-8 -*-
"""projeto-processador-de-vendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xL3dc3-9HzXYbxVSpHhbImnLN84I5l-
"""

def processar_vendas():

  total_compra: float = 0.0

  itens_comprados: int = 0



  quantidade_tipos: int = int(input("Quantos produtos diferentes foram comprados? "))



  for i in range(1, quantidade_tipos + 1):

    nome: str = input("Nome do produto: ")

    preco: float = float(input("Preço unitário: "))

    qtd: int = int(input("Quantidade deste produto: "))



    if preco <= 0 or qtd <= 0:

      print(f"Erro: Valores inválidos para {nome}")

    else:

      subtotal: float = preco * qtd

      total_compra += subtotal

      itens_comprados += qtd



  if total_compra > 500.00:

    total_final: float = total_compra * 0.90

    print("Desconto de 10% aplicado!")

  elif total_compra > 200.00:

    total_final = total_compra * 0.95

    print("Desconto de 5% aplicado!")

  else:

    total_final = total_compra



  print(f"Resumo: {itens_comprados} itens. Total a pagar: R$ {total_final:.2f}")





if __name__ == "__main__":

  processar_vendas()